version: '3'
services:
  back-end:
    depends_on:
      - mysqldb
    build: ./back-end
    restart: always
    container_name: back-end
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  front-end: 
    build: ./front-end
    container_name: front-end-cash-book
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

  mysqldb:
    image: mysql
    container_name: mysql-cash-book
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./cash_book_db.sql:/docker-entrypoint-initdb.d/cash_book_db.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-cash-book
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT 
    environment:  
      - PMA_USER= $PHPMYADMIN_USER
      - PMA_PASSWORD= $PHPMYADMIN_PASSWORD
      - PMA_HOST= mysqldb
    depends_on:
      - mysqldb
volumes: 
  db: